-- Script de Setup do Banco de Dados Supabase para o App "Nós Dois"
-- Abra o SQL Editor no painel do Supabase e rode:

-- 1. Criação das Tabelas
CREATE TABLE IF NOT EXISTS public.objectives (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator_name TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.shopping_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TIMESTAMPTZ NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  creator_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Configuração de Políticas RLS (Row Level Security)
-- Neste exemplo, permitimos acesso total anônimo já que o foco é comunicação de casal simples.
-- Se quiser mais segurança futuramente, você poderá habilitar a autenticação.
ALTER TABLE public.objectives ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for objectives" ON public.objectives FOR ALL USING (true);

ALTER TABLE public.shopping_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for shopping items" ON public.shopping_items FOR ALL USING (true);

ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for calendar events" ON public.calendar_events FOR ALL USING (true);

-- 3. Habilitar Realtime
-- Configura o Supabase para disparar eventos realtime nas 3 tabelas
begin; 
  drop publication if exists supabase_realtime; 
  create publication supabase_realtime; 
commit;
alter publication supabase_realtime add table public.objectives;
alter publication supabase_realtime add table public.shopping_items;
alter publication supabase_realtime add table public.calendar_events;
